Dev/reservation
finding-and-booking-tables-restaurants/eatpoint-backend pull request #16
Opened 2023-10-03 20:34 UTC by Xostyara

Сделано новое приложение для бронирований - reservation.
Выполнена модель бронирования в файле models.py.
добавлены остальные основные файлы

2023-10-03 21:38 UTC, Rashid-creator-droid requested changes

2023-10-03 21:39 UTC, Rashid-creator-droid requested changes

2023-10-03 21:39 UTC, Rashid-creator-droid commented on requirements.txt
> +asgiref==3.7.2
Это всё отменяй. Автодобаление не годится. Нужно оставить только те, который устанавливались через pip. Остальные автоматом ставятся и тут они не нужны.

2023-10-04 18:38 UTC, Xostyara commented on eatpoint/reservation/admin.py
> +from django.contrib import admin
Выполнено в новой версии

2023-10-04 18:41 UTC, Xostyara commented on eatpoint/reservation/models.py
> +    comment=models.CharField(
Выполнено в новой версии

2023-10-04 18:41 UTC, Xostyara commented on eatpoint/reservation/models.py
> +    event=models.ManyToManyField(
Выполнено

2023-10-04 18:42 UTC, Xostyara commented on eatpoint/reservation/models.py
> +class Restaurant_reservations(models.Model):
исправлено

2023-10-04 18:43 UTC, Xostyara commented on eatpoint/reservation/models.py
> +    """Список бронирований во всех ресторанах"""
исправлено

2023-10-05 07:38 UTC, Xostyara commented on eatpoint/reservation/models.py
> +User = get_user_model()
выполнено

2023-10-05 07:39 UTC, Xostyara commented on eatpoint/reservation/models.py
> +    Number_of_guests= models.CharField(
проверил. отображается один. но к ресторану можно привязать один и тот же стол несколько раз

2023-10-05 07:39 UTC, Xostyara commented on eatpoint/reservation/models.py
> +    Number_of_guests= models.CharField(
Поправлено, к ресторану привязывается 1 стол

2023-10-05 07:40 UTC, Xostyara commented on requirements.txt
> +asgiref==3.7.2
ок

2023-10-05 11:28 UTC, Rashid-creator-droid commented on eatpoint/reservation/models.py
> +    Number_of_guests= models.CharField(
Не к ресторану, а к бронированию. К ресторану можно привзяать нексолько столов т.к. может быть несколько столов у окна, на улице и т.д.

2023-10-09 21:33 UTC, Rashid-creator-droid requested changes

2023-10-09 21:33 UTC, Rashid-creator-droid commented on eatpoint/reservation/migrations/0001_initial.py
> +# Generated by Django 4.2.5 on 2023-10-03 21:24
миграции в гит игнор лучше убрать.

2023-10-09 21:33 UTC, Rashid-creator-droid commented on eatpoint/reservation/models.py
> +    table = models.ForeignKey(
ПМы решили отказаться от системы столов) Просто зона и кол-во мест.

2023-10-09 21:54 UTC, Rashid-creator-droid commented
Нужно обновлять ветку свою. Вью и сериализатор в папках, константы и саб функции в core. Там же и генератор для времени с интервалом 30 мин в choices. ПМ решили отказаться от системы столов и упростить задачу. Вместо модели стола модель ZoneEstablishment

2023-10-11 19:03 UTC, closed without merging