Dev/fix/auth with role
finding-and-booking-tables-restaurants/eatpoint-backend pull request #19
Opened 2023-10-04 20:03 UTC by ChernyaevAV

fix: добавил роли при создании пользователя, убрал телефон при создании суперюзера, пароль теперь захеширован

2023-10-04 21:50 UTC, Rashid-creator-droid requested changes
Ещё нужно доработать

2023-10-04 21:50 UTC, Rashid-creator-droid commented on eatpoint/api/serializers/user.py
>      telephone = serializers.CharField(
Тут можно убрать regex и поставить django-phonenumber-field. Я в модели заведения так сделал.

2023-10-04 21:50 UTC, Rashid-creator-droid commented on eatpoint/api/serializers/user.py
> +    role = serializers.ChoiceField(choices=settings.ROLE_CHOICES)
Роль не сохраняется
Пост запрос с ролью ресторатора
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/d2136cf2-8fab-4f18-a7b8-9e061af79e9f)
Гет запрос со списком пользователей, роль пишет user
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/4f7ff9fd-ec3d-4578-8ba0-5563a126405b)
Ещё хорошо бы было добавить в исключение какие есть допустимые значения, если пользователь ввел не правильную роль 
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/678fb428-27f1-4cf8-aeb1-98e863b5916f)

2023-10-04 21:50 UTC, Rashid-creator-droid commented on eatpoint/api/views/user.py
> +    permission_classes = (IsUser | IsRestaurateur,)
Тут я немного ошибся. Пермишн ресторатора нужно добавить в метод me, т.к. это профиль пользователя.
А тут нужно добавить метод только администратор, чтобы список пользователей мог смотреть только админ

2023-10-05 08:11 UTC, Rashid-creator-droid requested changes

2023-10-05 08:11 UTC, Rashid-creator-droid commented on eatpoint/api/views/user.py
>          url_path="me",
Не работает профиль пользователя
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/73671394-9398-4ad0-8ed0-f6c658ad82ba)

2023-10-05 17:51 UTC, Rashid-creator-droid requested changes

2023-10-05 17:51 UTC, Rashid-creator-droid commented on eatpoint/api/views/user.py
>      def me(self, request):
Не работает изменение данных юзера PATCH
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/0c12549c-845a-404c-b175-7416dd3e0390)
Админ тоже не может поменять данные по ID, лучше убрать возможность админа изменять данные пользователя

2023-10-05 20:27 UTC, Rashid-creator-droid requested changes

2023-10-05 20:27 UTC, Rashid-creator-droid commented on eatpoint/requirements.txt
> +asgiref==3.7.2
Автодобаление не нужно. Только то, что вручную писал в pip, остальные саб библиотеки сами подтянутся.

2023-10-05 20:27 UTC, Rashid-creator-droid commented on eatpoint/api/views/user.py
>          user, created = User.objects.get_or_create(
При попытке зарегать пользователя, который ввел секретный код, ещё раз с такими же данными выдаёт 
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/28588104-b626-442c-990c-5f14387d94e1)
Должен возвращать ответ в json

2023-10-05 20:27 UTC, Rashid-creator-droid commented on eatpoint/api/views/user.py
>          send_mail(
При попытке зарегать пользователя, который НЕ ввел секретный код, ещё раз, то вообще ничего не выдаёт.
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/8cce6d4c-60cd-41c2-9106-53826037a81a)
И спамит письмами каждый запрос.
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/d76a103c-c92c-43ef-9f93-5423e6b697c1)
Нужен ответ в json, что пользователю уже был отправлен код подтверждения и сделать ограничение на кол-во отправок писем раз в N-ое кол-во времени.

2023-10-05 20:27 UTC, Rashid-creator-droid commented on eatpoint/api/serializers/user.py
> +    password = serializers.CharField(write_only=True)
А ещё у нас не правильная логика работы системы регистрации) Пользователь регается, отправляет имя, фамилию, телефон, пароль, роль и почту. Затем высылается код поддтверждения на почту. Пользователь вводит этот код, с телефоном и согласием и получает токен. Вот только чтобы войти через день ему нужно снова ввести телефон, секретный код и подтверждение т.к. время жизни JWT-токена всего сутки, а получить код он не сможет, т.к. для этого нужно зарегаться ещё раз. Пароль в системе у нас отсутствует. Пользователь только 1 раз должен получать этот код, верифицировать свой профиль, а дальше входить по емейлу/телефону и паролю.

2023-10-05 20:29 UTC, Rashid-creator-droid commented on eatpoint/api/serializers/user.py
> +    password = serializers.CharField(write_only=True)
А ещё нужно ограничить время жизни кода подтверждения, иначе пользователь может входить по старому коду.

2023-10-05 20:36 UTC, Rashid-creator-droid commented on eatpoint/api/serializers/user.py
> +    password = serializers.CharField(write_only=True)
Ещё должно быть 2 поля для пароля, и пропускать, только если они совпадают.

2023-10-06 16:59 UTC, ChernyaevAV commented on eatpoint/api/views/user.py
>          send_mail(
сообщение приходит, но ограничить по количеству запросов пока не умею

2023-10-06 17:40 UTC, Rashid-creator-droid commented
так лучше даже, ввел, верефицировал акк, удалился код.

2023-10-06 18:56 UTC, ChernyaevAV commented on eatpoint/api/serializers/user.py
> +    password = serializers.CharField(write_only=True)
2 пароля пока не делал, думаю на этом этапе достаточно как есть. Позже подумаю над сбросом пароля

2023-10-06 18:57 UTC, ChernyaevAV commented on eatpoint/api/serializers/user.py
> +    password = serializers.CharField(write_only=True)
сделал обновление кода подтверждения

2023-10-06 18:57 UTC, ChernyaevAV commented on eatpoint/api/serializers/user.py
> +    password = serializers.CharField(write_only=True)
можно логинится по емейл и паролю

2023-10-06 20:27 UTC, Rashid-creator-droid requested changes
Может вернемся к стандартной авторизации/регистрации djsoer?

2023-10-06 20:27 UTC, Rashid-creator-droid commented on eatpoint/api/views/user.py
>              "is_agreement"
Нужно поправить, если пользователь ввел is_agreement false, то возвращает ответ, что он ввел не правильный код. Нужно чтобы возвратилось уведомление о том, что нужно согласиться с условием пользования.
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/bcb740f0-c0c4-4f36-9f46-17891442c4a7)

2023-10-06 20:27 UTC, Rashid-creator-droid commented on eatpoint/api/views/user.py
>      def post(self, request):
Получаю 2 токена по http://127.0.0.1:8000/api/v1/auth/confirm-code/ и http://127.0.0.1:8000/api/v1/auth/jwt/create/. Но ни по первому, ни по второму не могу авторизоваться.
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/65137a83-f812-4de8-9f74-c4ffe7d255c0)
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/60e55fd5-09c5-4cf0-be14-ec9c49d39574)
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/9e6f46a3-e86e-45a7-a4fb-97acd8a5d6c4)
Повторяются эндпоинты
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/8c52bcec-ddd6-4915-aa33-953a5e4a3dd8)
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/8c712e7a-79cc-4f33-8c73-68b3ff766715)

Снова при попытке отправить данные верифицированного пользователя выдает исключение, а не ответ в виде JSON
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/40574feb-010c-4ce4-a73f-31ee8b213055)

2023-10-07 09:36 UTC, ChernyaevAV commented on eatpoint/api/views/user.py
>      def post(self, request):
блин, никак не могу понять почему это перестало работать...

2023-10-08 18:24 UTC, Rashid-creator-droid commented on eatpoint/api/views/user.py
>              "is_agreement"
Не исправил

2023-10-08 18:48 UTC, Rashid-creator-droid requested changes

2023-10-08 18:48 UTC, Rashid-creator-droid commented on eatpoint/api/urls.py
>      path("v1/auth/confirm-code/refresh/", ConfirmCodeRefresh.as_view()),
Ничего не возвращает. Присылает проверочный код если даже пользователь уже подтвердил учетную запись. Должен возвращать какой-то ответ: если пользователь ещё не подтвердил, то отправлять "Код под. отправлен заноо", если пользователь уже подтвердил аккаунт, то "Вы уже подтвердили уч.запись"
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/6b9fe33c-c13d-4063-a38c-a5a7a5eafaac)

2023-10-08 18:48 UTC, Rashid-creator-droid commented on eatpoint/api/views/users.py
> +@extend_schema(tags=["Password"], methods=["POST"])
Нужно привести в порядок документацию. Названия не отображают смысл. 
Тут получить код подтверждения, хотя мы его уже получили.
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/49cf4892-f8ae-4066-b134-aa380c19fff3)
И это хозяйство нужно пристроить куда-то, а не просто в api и без описания
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/7c643ba0-0fc8-43fb-b625-e532ecc8ae78)

2023-10-08 18:49 UTC, Rashid-creator-droid requested changes

2023-10-08 18:49 UTC, Rashid-creator-droid commented on eatpoint/api/serializers/users.py
> +    first_name = serializers.CharField(
Нужно доработать валидатор или найти готовое решение. Такие именя не допустимы
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113050035/283067b2-2363-4eba-949e-edd37c8b979e)

2023-10-08 18:56 UTC, ChernyaevAV commented on eatpoint/api/views/user.py
>              "is_agreement"
исправил

2023-10-08 21:46 UTC, Rashid-creator-droid requested changes

2023-10-08 21:46 UTC, Rashid-creator-droid commented on eatpoint/requirements.txt
> +username-validator==0.0.1
Очень сомнительная библиотека, удали её я замержу и потом подумаем как лучше сделать)

2023-10-09 06:35 UTC, Rashid-creator-droid approved these changes

2023-10-09 06:35 UTC, merged