feat: добавил менеджер задач для периодической отправки сообщений о н…
finding-and-booking-tables-restaurants/eatpoint-backend pull request #235
Opened 2023-11-16 21:16 UTC by ChernyaevAV

feat: добавил менеджер задач celery для периодической отправки сообщений о необходимости подтверждения брони, пока существуют неподтвержденные. 
+ Исправил импорты
- нужно проверить docker-compose (я не уверен, что заработает с первого раза)

2023-11-17 10:07 UTC, Rashid-creator-droid requested changes

2023-11-17 10:07 UTC, Rashid-creator-droid commented on eatpoint/core/tasks.py
> +def send_message_for_confirm_booking():
Зачем подтверждение брони в celery? Подтверждение висит на вью (можно сделать на сигнал) и при создании записи о броинровании отправляется сообщение. 
На селери нужно повевсить оповещение клиента о брони за час, 30 мин и т.д, если пользователь поставил соответсвующий флаг. Эти флаги есть в модели бронирования.

2023-11-17 10:07 UTC, Rashid-creator-droid commented on eatpoint/core/tasks.py
> +def send_message_for_confirm_booking_by_id(_id):
Тут тоже самое. Оповещение клиента, а не ресторатора. Ресторатору хватит и 1 раза при создании бронирования без селери.

2023-11-17 10:07 UTC, Rashid-creator-droid commented on eatpoint/eatpoint/settings.py
> +CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
нужно переменные добвать в env.example

2023-11-17 10:07 UTC, Rashid-creator-droid commented on infra/docker-compose.yml
> +  redis:
Локально в докере работает?

2023-11-17 18:51 UTC, ChernyaevAV commented on eatpoint/core/tasks.py
> +def send_message_for_confirm_booking():
Напоминания для администратора ресторана нужно, об этом сказали на первой презентации.
Напоминания для клиентов сделаю попозже.

2023-11-17 18:52 UTC, ChernyaevAV commented on eatpoint/eatpoint/settings.py
> +CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
жестко прописал в сеттингс. менять не будем

2023-11-17 18:52 UTC, ChernyaevAV commented on eatpoint/core/tasks.py
> +def send_message_for_confirm_booking_by_id(_id):
Напоминания для администратора ресторана нужно, об этом сказали на первой презентации.
Напоминания для клиентов сделаю попозже.

2023-11-18 07:57 UTC, Rashid-creator-droid commented on eatpoint/core/tasks.py
> +def send_message_for_confirm_booking():
Создалась бронь, пришло уведомление на почту. Всё это делается без селери. Зачем ещё спамить напоминания? Это просто будет засорять и без того нагруженную почту заведения. Напоминания нужны только клиенту

2023-11-18 07:57 UTC, Rashid-creator-droid commented on eatpoint/core/tasks.py
> +def send_message_for_confirm_booking_by_id(_id):
Создалась бронь, пришло уведомление на почту. Всё это делается без селери. Зачем ещё спамить напоминания? Это просто будет засорять и без того нагруженную почту заведения. Напоминания нужны только клиенту

2023-11-25 20:48 UTC, closed without merging