fix убраны поля review и owner, привязан ответ к отзыву
finding-and-booking-tables-restaurants/eatpoint-backend pull request #248
Opened 2023-11-22 10:06 UTC by SemenovY

Убрал эти поля. данные берутся из реквеста.
Ответ привязан к отзыву, при гет запросе отзыва, получаем ответ в поле response либо null

2023-11-22 10:15 UTC, Rashid-creator-droid requested changes

2023-11-22 10:15 UTC, Rashid-creator-droid commented on eatpoint/api/views/establishments.py
> +        if establishment_owner != review.establishment.owner:
permission_classes нужно настроить доступ через пермишн. Там вроде даже есть, хозяин заведения уже. Тут убрать исключение.

2023-11-22 10:15 UTC, Rashid-creator-droid commented on eatpoint/establishments/admin.py
> +    list_display = ("id", "text", "created")
это поле отображение на главной странице выборе ответов.  Лучше тут оставить поле ревью, а убрать поле текст. А поле id и ревью поменять местами в порядке, т.к. тыкать на маленький значек ид трудно.

2023-11-23 13:37 UTC, SemenovY commented on eatpoint/api/views/establishments.py
> +        if establishment_owner != review.establishment.owner:
Поправил.
Добавил отдельную проверку в пермишены для владельца ресторана IsEstablishmentOwner.
Различие заключается в том, что IsRestorateurEdit проверяет роль пользователя: в has_permission - наличие роли ресторатора у аутентифицированного пользователя, а в has_object_permission - проверяется, является ли пользователь владельцем заведения, связанного с объектом.

2023-11-24 16:26 UTC, Rashid-creator-droid approved these changes

2023-11-24 16:26 UTC, merged