feat: добавлен celery для периодических напоминаний клиенту о бронировании
finding-and-booking-tables-restaurants/eatpoint-backend pull request #252
Opened 2023-11-25 23:10 UTC by ChernyaevAV

feat: добавлен celery для периодических напоминаний клиенту о бронировании (за 1 день, за 3 часа, за 30 мин)

2023-11-29 18:28 UTC, Rashid-creator-droid requested changes

2023-11-29 18:28 UTC, Rashid-creator-droid commented on infra/docker-compose.yml
> +    image: valentaine98/eatpoint-backend:latest
это зачем? я чет не понял зачем скачивать и создавать ещё раз:?

2023-11-29 18:28 UTC, Rashid-creator-droid commented on infra/docker-compose.yml
> +    image: valentaine98/eatpoint-backend:latest
тут тоже самое, зачем это вообще нужно? образ бэка создается в backend зачем повторять его 2 раза?

2023-11-29 18:28 UTC, Rashid-creator-droid commented on eatpoint/Dockerfile
> +RUN chmod +x /app/flower-entrypoint.sh
нужно убрать infra запихнуть все зависимые в папку eatpoint. В папке infra хранятся только .енв, компот и nginx. Эту папку я закидываю на сервер и flower-entrypoint.sh 
worker-entrypoint.sh 
beat-entrypoint.sh этим файлам там делать нечего, они никак не будут использованы

2023-11-29 18:41 UTC, ChernyaevAV commented on infra/docker-compose.yml
> +    image: valentaine98/eatpoint-backend:latest
worker и beat запускается в отдельных контейнерах, а им нужны модели джанги

2023-11-29 18:43 UTC, ChernyaevAV commented on infra/docker-compose.yml
> +    image: valentaine98/eatpoint-backend:latest
worker и beat запускается в отдельных контейнерах, а им нужны модели джанги

2023-12-15 13:44 UTC, ratarov commented on eatpoint/Dockerfile
> +RUN chmod +x /app/flower-entrypoint.sh
Андрей просил поддержки, но прости, Андрей) 
Я не успел пока поработать с celery на живом проекте, но, мне кажется, тут эти файлы вообще не нужны. Все эти команды я видел в чужих докер-композах просто в теге command
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113984061/706d603b-5cbe-49b9-8161-307e4f4c4ddd)
![image](https://github.com/finding-and-booking-tables-restaurants/eatpoint-backend/assets/113984061/ec70dbd5-3a33-4de7-b3a4-fdcbef91ef3f)

2023-12-15 13:53 UTC, ratarov commented on eatpoint/core/tasks.py
> +        reminder_time = booking_date_time - timedelta(minutes=30)
мне кажется, тут жесткий хардкодинг (я про 30 минут/3 часа/1день).
плюс нарушается DRY: 87-98 просто повторяется 3 раза.
я бы предложил напоминания вынести в отдельную модель; это сделает модели более расширяемыми, процесс напоминаний станет более настраиваемым, код - чище

2023-12-15 16:55 UTC, ChernyaevAV commented on eatpoint/Dockerfile
> +RUN chmod +x /app/flower-entrypoint.sh
Да, я в теме. так было с самого начала, но похоже у винды есть проблемы с докером. у меня очень долгое время не получалось запустить контейнеры.... а я хотель протестить сначала локально. сейчас сделал также

2023-12-15 16:56 UTC, ChernyaevAV commented on eatpoint/core/tasks.py
> +        reminder_time = booking_date_time - timedelta(minutes=30)
сейчас была задача чтобы работало. поэтому пока так. дальше будет рефакторить

2023-12-24 21:28 UTC, closed without merging